# Generated by Django 5.2.6 on 2025-10-03 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.IntegerField(blank=True, max_length=11)),
                ('tg', models.CharField(blank=True, help_text='Enter your Telegram username, That you want client to contact you on', max_length=30)),
                ('fb', models.CharField(blank=True, help_text='Enter your Facebook username, That you want client to contact you on', max_length=30)),
                ('ig', models.CharField(blank=True, help_text='Enter your Instagram username, That you want client to contact you on', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
