# Generated by Django 5.2.6 on 2025-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.PositiveIntegerField(blank=True, max_length=10),
        ),
    ]
