# Generated by Django 5.2.6 on 2025-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
