# Generated by Django 5.2.6 on 2025-10-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_generatedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcode',
            name='path',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
