# Generated by Django 5.2.6 on 2025-10-03 10:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationType', models.CharField(choices=[('RENTING', 'إيجار'), ('SELLING', 'بيع')], default='RENTING', max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('length', models.FloatField(max_length=5)),
                ('width', models.FloatField(max_length=5)),
                ('faces', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2)),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('municipality', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OCCUPIED', 'مشغول'), ('UNOCCUPIED', 'غير مشغول')], default='UNOCCUPIED', max_length=20)),
                ('available_from', models.DateField(blank=True, help_text='If the house is in use, specify when it will be unoccupied.', null=True)),
                ('access_hash', models.CharField(editable=False, max_length=32, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.house')),
            ],
        ),
    ]
